# Generated by Django 5.0 on 2025-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_created=True)),
                ('update', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_created=True)),
                ('update', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('review', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-id'],
            },
        ),
    ]
