# Generated by Django 5.0 on 2025-05-22 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='creation',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
