# Generated by Django 5.0 on 2025-05-22 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_course_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
