# Generated by Django 5.0 on 2025-06-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_creation_alter_review_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to='course/thumbnail/%Y/%m/%d/'),
        ),
    ]
