# Generated by Django 5.0 on 2025-06-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('INICIANTE', 'Iniciante'), ('INTERMEDIÁRIO', 'Intermediário'), ('AVANÇADO', 'Avançado')], default='INICIANTE', max_length=100),
        ),
    ]
