# Generated by Django 5.0 on 2025-02-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_user_review_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course',)},
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
