# Generated by Django 5.0 on 2025-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_duration_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course/thumbnail/%Y/%m/%d/'),
        ),
    ]
