# Generated by Django 5.0 on 2025-06-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
    ]
