# Generated by Django 5.1.4 on 2024-12-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_created=True)),
                ('update', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_created=True)),
                ('update', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('review', models.DecimalField(decimal_places=1, max_digits=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='courses.course')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'unique_together': {('email', 'course')},
            },
        ),
    ]
